### ISSUE TITLE
BFGS+EM for optimising model parameters

### ISSUE THREAD

**Issue by roblanf** [iqtree/iqtree2#1]
The other day we discussed which algorithm was better for model parameter estimation. We have two implementations:

1. EM, which will fix all parameters and optimise each one in turn while holding the others fixed, then iterate until it's done.

2. BFGS, which will optimise all parameters at once

@bqminh mentioned that in the original modelfinder, they had compared these and found that BFGS was quicker but gave worse likelihoods, so they decided to stick with EM.

@JamesBarbetti mentioned that often it's better to chain them together

I said I'd take a look at the huge SARS-CoV-2 alignments and see what happened. Here's what happened, confirming that this is hard and also interesting. This is an alignment of ~30K bp and ~40K sequences. Free rate models fit much better than the other models. 

JC+I+R5 optimised with EM:
lnL: -388587.635
Proportion of invariable sites: 0.389
Site proportion and rates:  (0.529,0.808) (0.074,5.739) (0.009,16.933)

JC+I+R5 optimised with BFGS:
lnL: <-375974.923841
Proportion of invariable sites: 0.616
Site proportion and rates:  (0.426,0.269) (0.415,0.625) (0.159,3.936)

It's less than that because I had to kill the analysis before it had a chance to do the final round of fine-grained model parameter optimisations. The first analysis took about 2 days. I killed the second on after 1 day, and I'd guess it was going to take a fairly similar total execution time compared the first one. BFGS is certainly no more than twice as fast. 

The surprise: BFGS got WAY better likelihoods. 

So, my suggestion is that we implement @JamesBarbetti's suggestion of the two algorithms chained together and compare the performance on a range of datasets. I guess there are lots of options for how to chain them, including:

1. BFGS until convergence followed EM until convergence
2. As in 1 but EM followed by BFGS
3. Switch between BFGS and EM on each iteration

@JamesBarbetti suggested that option 3 might be best, and that's my intuition too. 

I think this could be a nice addition to ModelFinder2, and simple to compare on a representative datasets.

**Comment by bqminh** [comment]
tagging @thomaskf here for discussions.
That's interesting. What Lars and Thomas did, was not exactly about log-likelihoods but about accuracy. So they simulated a bunch of alignments and free-rates, and ask whether BFGS or EM most frequently obtained the the true rates back. And the answer was EM.
I remember that, I also did a bunch of empirical alignments, and observed that none of them always obtained higher likelihood than the other. Sometimes BFGS got higher likelihood, sometimes EM.
@roblanf 's suggestion is sensible. I believe Thomas put such code in IQ-TREE after our meeting. Thomas, can you pls test this data set?

**Comment by roblanf** [comment]
@thomaskf if you can post the relevant commandline here, I can test it on this dataset (it's a GISAID dataset so hard to share).

**Comment by roblanf** [comment]
Also I'm not totally convinced about simulating data and then asking whether we get the 'true' rates back. We only expect to get the 'true' rates if we have infinite species (well, infinite tree length really) and infinite sites. 

E.g. if the number of species is limited, more and more sites will look like constant sites rather than sites from a 'true' low rate category. Because of these limitations, I tend to think that in ML software we should really consider the methods (within reason, of course!) that give us the best likelihood. If that disagrees with simulation conditions, it will often be because of some other limitation.

**Comment by thomaskf** [comment]
@roblanf sorry for the late reply. I agree with your point. I have updated the codes last Saturday so that in each iteration 1-BFGS->EM is performed, and the iteration will be repeated until the convergence is reached. I am uploading the codes soon so that you can have a test. Meanwhile, I still need a bit more time to finalize the paper with Allen and I will work at full speed on the project starting from next week. Apology for the delay and the inconvenience caused.

**Comment by roblanf** [comment]
Hi @thomaskf, that sounds good. Just make sure that the three algorithms are available as different flags:

1. one for EM only
2. one for BFGS only
3. one for EM/BFGS combined

**Comment by bqminh** [comment]
@thomaskf : I don't think 1-BFGS->EM a good approach, because after doing BFGS, you will be in a local optimum. If you now start EM from that local optimum, I don't see how it help to escape it, except for moving a bit around it. It's better to have independent starting points, with/without different algorithms. Since this is quite a long time with no sensible solution, I recommend that we close this discussion, also because everyone is busy with other projects and we don't really have person to pursue it further, esp. in testing different approaches.
