### ISSUE TITLE
speed up the candidate tree set generation

### ISSUE THREAD

**Issue by AndreaAguadoM** [iqtree/iqtree2#115]
Hello, my name is Andrea and I am a bioinformatitian here in Spain. 
Currrently, I am trying to a analyze a 6900 sequence set, but the iqtree tree generation process is taking too long. Specifically, it has been working for 5 days and the process's still not done. The line I use in order to make use of the tool is the following: 

iqtree2 -s $dir/alignment.fasta -T 52. 

Should I be using more resources or could you give me some other advice? 
Thanks in advance!

**Comment by bqminh** [comment]
You can try -fast option to turn on fast tree search mode, to see if that helps.

Cheers
Minh
________________________________
From: AndreaAguadoM ***@***.***>
Sent: Tuesday, 3 January 2023 12:34 AM
To: iqtree/iqtree2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [iqtree/iqtree2] speed up the candidate tree set generation (Issue #115)


Hello, my name is Andrea and I am a bioinformatitian here in Spain.
Currrently, I am trying to a analyze a 6900 sequence set, but the iqtree tree generation process is taking too long. Specifically, it has been working for 5 days and the process's still not done. The line I use in order to make use of the tool is the following:

iqtree2 -s $dir/alignment.fasta -T 52.

Should I be using more resources or could you give me some other advice?
Thanks in advance!

**Comment by AndreaAguadoM** [comment]
It does not work either... It's been running for 27 hours now even turning on the -fast option.

**Comment by bqminh** [comment]
Sorry for dropping the ball. How many CPU cores does your computer have? Let assume for now that you have more than 52.

The next question is: how many sites do you have in your alignment? If not many, `-T 52` can be way too many threads, that may even slow down the analysis. The multi-threading scales with the number of sites, not the number of sequences. A good practice is to use `-T AUTO` to let IQ-TREE determine the best number of threads by itself.

Let assume that you have a lot of sites: then 6900 is just way too large dataset for IQ-TREE. In the mean time, we have improved the code and you can test the latest version 2.3.4.

For now I will assume that this issue is resolved. But if that's not the case, feel free to reopen this issue.
