### ISSUE TITLE
nan in test of symmetry

### ISSUE THREAD

**Issue by hyyuu** [iqtree/iqtree2#118]
Hello ! 

I am running the e tests of symmetry on my data. I found there are quite many "nan" in the columns of MarPval and IntPval. May I ask what does it mean ? Is it an implication of any problematic data ?
Thank you for your help and your constant effort ! 

Best, 
Alex

**Comment by bqminh** [comment]
Hi Alex,

NaN means "not a number". It means that there is not enough data to estimate a p-value, typically because you have a very short corresponding alignment.

Cheers
Minh

---
Minh Bui, PhD
Senior Lecturer
School of Computing, Australian National University
Canberra, ACT 2600, Australia
Hanna Neumann Building, Room 4.16
145 Science Rd
https://bqminh.github.io

On 10 Jan 2023, at 4:06 am, hyyuu ***@***.***> wrote:



Hello !

I am running the e tests of symmetry on my data. I found there are quite many "nan" in the columns of MarPval and IntPval. May I ask what does it mean ? Is it an implication of any problematic data ?
Thank you for your help and your constant effort !

Best,
Alex

**Comment by hyyuu** [comment]
Hi Minh, 

Thank you for your prompt reply ! As I tried the tests on trimmed alignments, I will try again on a untrimmed one. Thank you again!

Best, 
Alex
