### ISSUE TITLE
segfault on large analysis

### ISSUE THREAD

**Issue by roblanf** [iqtree/iqtree2#123]
Hey @thomaskf and @bqminh, Fred and I are trying to build a large tree of 66K sequences and IQ-TREE is giving us a segfault when computing ML distances.

The alignment is here: https://github.com/fredjaya/gtdb_trees/blob/main/alignments/gtdb_r207_bac120_concatenated.faa.xz

Can be decompressed with `xz -d`. I'm happy to run any additional analyses though!

Right now I've tried restarting the analysis on a single thread to see what happens, though presumably it'll take a while...

R

```
iqtree2 -s gtdb_r207_bac120_concatenated.faa -m LG -fast -nt 32
IQ-TREE multicore version 2.2.0.3 COVID-edition for Linux 64-bit built Aug  2 2022
Developed by Bui Quang Minh, James Barbetti, Nguyen Lam Tung,
Olga Chernomor, Heiko Schmidt, Dominik Schrempf, Michael Woodhams, Ly Trong Nhan.

Host:    rona.rsb.anu.edu.au (AVX2, FMA3, 1007 GB RAM)
Command: iqtree2 -s gtdb_r207_bac120_concatenated.faa -m LG -fast -nt 32
Seed:    683354 (Using SPRNG - Scalable Parallel Random Number Generator)
Time:    Wed Feb 15 11:23:51 2023
Kernel:  AVX+FMA - 32 threads (256 CPU cores detected)

Reading alignment file gtdb_r207_bac120_concatenated.faa ... Fasta format detected
Reading fasta file: done in 6.49711 secs using 91.06% CPU
Alignment most likely contains protein sequences
Constructing alignment: done in 5.14388 secs using 87.45% CPU
Alignment has 62291 sequences with 5036 columns, 5036 distinct patterns
5036 parsimony-informative, 0 singleton sites, 0 constant sites
Analyzing sequences: done in 0.199267 secs using 2402% CPU
WARNING: 1011 sequences contain more than 50% gaps/ambiguity
Checking for duplicate sequences: done in 6.58733 secs using 175.8% CPU

Create initial parsimony tree by phylogenetic likelihood library (PLL)... 29091.58 seconds

NOTE: 48657 MB RAM (47 GB) is required!
Estimate model parameters (epsilon = 0.50)
1. Initial log-likelihood: -139926704.65
Optimal log-likelihood: -138593932.66
Parameters optimization took 1 rounds (28089.44 sec)
Wrote distance file to... 
Computing ML distances based on estimated model parameters...
ERROR: 
ERROR: *** IQ-TREE CRASHES WITH SIGNAL SEGMENTATION FAULT
ERROR: *** For bug report please send to developers:
ERROR: ***    Log file: gtdb_r207_bac120_concatenated.faa.log
ERROR: ***    Alignment files (if possible)
Segmentation fault (core dumped)
```

**Comment by bqminh** [comment]
I believe this is because the code for distance-based trees does not work with more than 64K sequences.

Can you re-try with an earlier version, like 1.6.12 and check if it works?

Minh

---

On 16 Feb 2023, at 12:03 pm, roblanf ***@***.***> wrote:



Hey @thomaskf<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthomaskf&data=05%7C01%7Cm.bui%40anu.edu.au%7C5ede535b32b14962bf9e08db0fb9ac47%7Ce37d725cab5c46249ae5f0533e486437%7C0%7C0%7C638121062356038053%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=K%2Fi4PdlheIWs5veDV4g0MYDlsyIOI%2Bscrc543eWV9AI%3D&reserved=0> and @bqminh<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbqminh&data=05%7C01%7Cm.bui%40anu.edu.au%7C5ede535b32b14962bf9e08db0fb9ac47%7Ce37d725cab5c46249ae5f0533e486437%7C0%7C0%7C638121062356038053%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=SoQkGRkUCGaR0Yowxqwbo8pyJLM8j3pJ%2Bs%2F0ZEpCRJE%3D&reserved=0>, Fred and I are trying to build a large tree of 66K sequences and IQ-TREE is giving us a segfault when computing ML distances.

The alignment is here: https://github.com/fredjaya/gtdb_trees/blob/main/alignments/gtdb_r207_bac120_concatenated.faa.xz<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffredjaya%2Fgtdb_trees%2Fblob%2Fmain%2Falignments%2Fgtdb_r207_bac120_concatenated.faa.xz&data=05%7C01%7Cm.bui%40anu.edu.au%7C5ede535b32b14962bf9e08db0fb9ac47%7Ce37d725cab5c46249ae5f0533e486437%7C0%7C0%7C638121062356038053%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WGqni0%2Fls6PqZ6dNYpVmHRcJ1wmKDGoLz%2BF%2FU8Bwcus%3D&reserved=0>

Can be decompressed with xz -d. I'm happy to run any additional analyses though!

Right now I've tried restarting the analysis on a single thread to see what happens, though presumably it'll take a while...

R

iqtree2 -s gtdb_r207_bac120_concatenated.faa -m LG -fast -nt 32
IQ-TREE multicore version 2.2.0.3 COVID-edition for Linux 64-bit built Aug  2 2022
Developed by Bui Quang Minh, James Barbetti, Nguyen Lam Tung,
Olga Chernomor, Heiko Schmidt, Dominik Schrempf, Michael Woodhams, Ly Trong Nhan.

Host:    rona.rsb.anu.edu.au (AVX2, FMA3, 1007 GB RAM)
Command: iqtree2 -s gtdb_r207_bac120_concatenated.faa -m LG -fast -nt 32
Seed:    683354 (Using SPRNG - Scalable Parallel Random Number Generator)
Time:    Wed Feb 15 11:23:51 2023
Kernel:  AVX+FMA - 32 threads (256 CPU cores detected)

Reading alignment file gtdb_r207_bac120_concatenated.faa ... Fasta format detected
Reading fasta file: done in 6.49711 secs using 91.06% CPU
Alignment most likely contains protein sequences
Constructing alignment: done in 5.14388 secs using 87.45% CPU
Alignment has 62291 sequences with 5036 columns, 5036 distinct patterns
5036 parsimony-informative, 0 singleton sites, 0 constant sites
Analyzing sequences: done in 0.199267 secs using 2402% CPU
WARNING: 1011 sequences contain more than 50% gaps/ambiguity
Checking for duplicate sequences: done in 6.58733 secs using 175.8% CPU

Create initial parsimony tree by phylogenetic likelihood library (PLL)... 29091.58 seconds

NOTE: 48657 MB RAM (47 GB) is required!
Estimate model parameters (epsilon = 0.50)
1. Initial log-likelihood: -139926704.65
Optimal log-likelihood: -138593932.66
Parameters optimization took 1 rounds (28089.44 sec)
Wrote distance file to...
Computing ML distances based on estimated model parameters...
ERROR:
ERROR: *** IQ-TREE CRASHES WITH SIGNAL SEGMENTATION FAULT
ERROR: *** For bug report please send to developers:
ERROR: ***    Log file: gtdb_r207_bac120_concatenated.faa.log
ERROR: ***    Alignment files (if possible)
Segmentation fault (core dumped)

**Comment by roblanf** [comment]
I'll give it a shot. I'll also try with a MP starting tree from somehwere else. Presumably that will avoid distance calculations?

**Comment by roblanf** [comment]
@bqminh is right. If I run the analysis without trying to use an NJ starting tree it works fine.

So I have two suggestions:

1. If the dataset is >64K, then just drop down to estimating a single parsimony starting tree

or 

2. If the dataset is >64K and the user is trying to get an NJ tree for any reason, (including as a starting tree), then exit with an error which says "You are trying to estimate an NJ tree for >64K taxa, which is not possible in IQ-TREE. If you were running a standard analysis, the NJ tree would have been used as a starting tree. To avoid this, please use the `-t PARS` option to use parsimony starting trees, or provide a starting tree from somehwere else".
