### ISSUE TITLE
Unable to compile on macOS, ARM64

### ISSUE THREAD

**Issue by victorlin** [iqtree/iqtree2#126]
I am following the [compilation guide](http://www.iqtree.org/doc/Compilation-Guide).

`cmake` is successful, however `make -j` gives several warnings/errors. Some notable lines ([full output](https://github.com/iqtree/iqtree2/files/10985344/iqtree-make-output.txt)):

```
clang: error: the clang compiler does not support '-march=native'

clang: warning: argument unused during compilation: '-msse3' [-Wunused-command-line-argument]

vectorclass/vectorclass.h:38:4: error: Please compile for the SSE2 instruction set or higher

vectorclass/vectormath_common.h:65:8: error: unknown type name 'Vec2d'

vectorclass/instrset_detect.cpp:26:10: error: couldn't allocate output register for constraint 'a'

/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include/xmmintrin.h:14:2: error: "This header is only meant to be used on x86 and x64 architecture"

/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include/mmintrin.h:54:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
```

Is there something I am missing here?

**Comment by victorlin** [comment]
I can confirm all the requirements are met:

- [x] C++

    <details>
    <summary>details</summary>

    ```
    % which c++
    /usr/bin/c++
    ```

    </details>


- [x] CMake version >= 2.8.10

    <details>
    <summary>details</summary>

    ```
    % cmake --version
    cmake version 3.26.0

    CMake suite maintained and supported by Kitware (kitware.com/cmake).
    ```

    </details>


- [x] Boost library

    <details>
    <summary>details</summary>

    From the output of `cmake`:

    ```
    -- Found Boost: /opt/homebrew/Caskroom/miniconda/base/envs/build-iqtree/lib/cmake/Boost-1.81.0/BoostConfig.cmake (found version "1.81.0")  
    ```

    </details>


- [x] Eigen3 library

    <details>
    <summary>details</summary>

    ```
    % brew info eigen 
    ==> eigen: stable 3.4.0 (bottled), HEAD
    C++ template library for linear algebra
    https://eigen.tuxfamily.org/
    Conflicts with:
      freeling (because freeling ships its own copy of eigen)
    /opt/homebrew/Cellar/eigen/3.4.0_1 (546 files, 8.4MB) *
      Poured from bottle on 2023-03-15 at 16:19:46
    ```

    </details>

- [x] OpenMP library

    <details>
    <summary>details</summary>

    ```
    % brew info libomp
    ==> libomp: stable 15.0.5 (bottled) [keg-only]
    LLVM's OpenMP runtime library
    https://openmp.llvm.org/
    /opt/homebrew/Cellar/libomp/15.0.5 (7 files, 1.6MB)
      Poured from bottle on 2022-11-28 at 17:19:46
    ```

    </details>

**Comment by victorlin** [comment]
Oh, I just realized I am using an older version (2.1.2, the latest GitHub Release) which does not include 44bfe3d2a456034c6e3203467cf5ef836a729ad6. I tried using v2.2.2.3 but am now facing a `cmake` error. I will investigate more tomorrow.

**Comment by bqminh** [comment]
Currently, IQ-TREE does not support the new Mac M1/2 processors. There has been some effort to support this, but may only come in the near future.

Re. requirements, yes that’s all needed to compile IQ-TREE.


On 16 Mar 2023, at 10:57 am, Victor Lin ***@***.***> wrote:



I can confirm all the requirements are met:

  *    C++

details

% which c++
/usr/bin/c++


  *    CMake version >= 2.8.10

details

% cmake --version
cmake version 3.26.0

CMake suite maintained and supported by Kitware (kitware.com/cmake).


  *    Boost library

details

From the output of cmake:

-- Found Boost: /opt/homebrew/Caskroom/miniconda/base/envs/build-iqtree/lib/cmake/Boost-1.81.0/BoostConfig.cmake (found version "1.81.0")


  *    Eigen3 library

details

% brew info eigen
==> eigen: stable 3.4.0 (bottled), HEAD
C++ template library for linear algebra
https://eigen.tuxfamily.org/
Conflicts with:
  freeling (because freeling ships its own copy of eigen)
/opt/homebrew/Cellar/eigen/3.4.0_1 (546 files, 8.4MB) *
  Poured from bottle on 2023-03-15 at 16:19:46


  *    OpenMP library

details

% brew info libomp
==> libomp: stable 15.0.5 (bottled) [keg-only]
LLVM's OpenMP runtime library
https://openmp.llvm.org/
/opt/homebrew/Cellar/libomp/15.0.5 (7 files, 1.6MB)
  Poured from bottle on 2022-11-28 at 17:19:46

**Comment by corneliusroemer** [comment]
I managed to compile (on arm 12/13) with the following homebrew recipe (should make it possible to reproduce for anyone without differing local setup): https://github.com/Homebrew/homebrew-core/blob/573b15f29e31ba4143ae8137111cf87a3f181829/Formula/iqtree2.rb

But compared with using the official osx-64 binary, iqtree seems to get stuck a lot in substitution model fitting with errors/warnings like:

```log
ERROR: Numerical underflow (lh-derivative). Run again with the safe likelihood kernel via -safe option
```

Running the official osx-64 binary, I don't get any such warning.

**Comment by thomaskf** [comment]
Dear Cornelius,

Thanks for your interest in IQ-TREE. However, I am afraid that IQ-TREE is
currently not fully compatible with M1 or M2 MacBook devices. We have been
working on this.

Thomas

**Comment by iqtree** [comment]
We now added support for Apple M chips in v2.3.X

**Comment by corneliusroemer** [comment]
Thank you, that's great! I managed to compile after experimenting a bit. This is the recipe that worked in the end. Could you check whether that's the same you use? I couldn't find up to date documentation on how exactly you build on arm macs.

This worked for me:

```bash
gh repo clone iqtree/iqtree2
cd iqtree2
git submodule init
git submodule update
mkdir build
cd build
cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_FLAGS="-Dthread_local=" ..
make -j
```

Also see my docs PR at https://github.com/iqtree/iqtree.github.io/pull/3
