### ISSUE TITLE
Continue the program after filter out invariant sites

### ISSUE THREAD

**Issue by xiekunwhy** [iqtree/iqtree2#139]
Hi,

iqtree always stop runing after filtering out invariant sites.
Is there an option to continue the analysis after filtering instead of stop the program?

Best,
Kun

**Comment by thomaskf** [comment]
Hi Kun,

Which version are you using? Can you try the latest version, like 2.2.3 or 2.2.4 (https://github.com/iqtree/iqtree2/releases), because some bugs have been fixed recently?

If the problem still exists, can you please send us the log file for more information?

Thanks,
Thomas

From: xiekunwhy ***@***.***>
Date: Thursday, 7 September 2023 at 1:18 pm
To: iqtree/iqtree2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [iqtree/iqtree2] Continue the program after filter out invariant sites (Issue #139)

Hi,

iqtree always stop runing after filtering out invariant sites.
Is there an option to continue the analysis after filtering instead of stop the program?

Best,
Kun

**Comment by bqminh** [comment]
I'm assuming that you used `+ASC` model. We intentionally stopped the run, so that users are conscious of the problem in their input data. At the same time IQ-TREE prints `.varsites.phy` file with only variable sites included, so that you can start a second run on this file. So I don't think there is any problem with that, and I don't plan to just allow to run `+ASC` on the original data.
