### ISSUE TITLE
lsd2 folder empty when compiling

### ISSUE THREAD

**Issue by TheGreatJack** [iqtree/iqtree2#153]
I compiled [iqtree-mpi v2.2.2.7](https://github.com/iqtree/iqtree2/releases/tag/v2.2.2.7). I followed the [compilation guide](http://www.iqtree.org/doc/Compilation-Guide). But it appears that the lsd2 folder is empty and it threw me the error "lsd2 doesn't contain a CMakeLists.txt file". I had to download the source code of [lsd2](https://github.com/tothuhien/lsd2/releases/tag/v.2.4.1) and copy that into the iqtree source code folder. It feels like the release should include lsd2.  I'm not sure if it has something to do with lsd2 being a separate project.  

I used: openmpi 4.1.2, cmake 3.27.7, gcc 11.2 and boost 1.78 (modules i had to load in the server i work)

**Comment by trongnhanuit** [comment]
Dear Florian,
Thank you for reporting the issue.

Since we included lsd2 as a sub-module, you can use "--recursive" flag to
clone iqtree2 and its sub-modules like:

*git clone --recursive https://github.com/iqtree/iqtree2.git
<https://github.com/iqtree/iqtree2.git>*


It could resolve that problem.
Please feel free to contact us if you have any questions.

Cheers,
Nhan

**Comment by bwesen** [comment]
You can also use "git submodule update --init --recursive" after cloning if you forgot the --recursive option in the first place.

You could close this ticket, this is the right solution

**Comment by corneliusroemer** [comment]
Don't close, improve the documentation, e.g. here: http://www.iqtree.org/doc/Compilation-Guide

I encountered the same issue in #169

**Comment by thomaskf** [comment]
Thanks! The documentation has been updated.
