### ISSUE TITLE
Wrong number of states detected for a morphological alignment

### ISSUE THREAD

**Issue by davidcerny** [iqtree/iqtree2#344]
**Bug description**

When trying to run an analysis of discrete morphological data partitioned by state number, IQ-TREE can misidentify multistate characters as binary ones.

**To reproduce**

In [this dataset](https://github.com/user-attachments/files/17611664/lab5stuff.zip), the file `Tedford_2009_ORDERED3.phy` contains 6 characters (and 6 unique patterns), each of which takes three unambiguous states: `0`, `1`, and `2`. However, when I try to analyze it as follows:

```
./iqtree2 -p partitions.nex -pre canids_partitioned -o Hesperocyoninae -b 1000 -T AUTO
```

IQ-TREE says the alignment "most likely contains binary sequences", and throws an error whenever it encounters state `2`:

```
Reading alignment file Tedford_2009_ORDERED3.phy ... Phylip format detected
Alignment most likely contains binary sequences
ERROR: Sequence Cuon_javanicus has invalid character 2 at site 1
ERROR: Sequence Lycaon_pictus has invalid character 2 at site 1
ERROR: Sequence Urocyon_cinereoargenteus has invalid character 2 at site 2
ERROR: Sequence Urocyon_minicephalus has invalid character 2 at site 3
ERROR: Sequence Urocyon_cinereoargenteus has invalid character 2 at site 3
ERROR: Sequence Canis_lupus has invalid character 2 at site 4
ERROR: Sequence Canis_latrans has invalid character 2 at site 5
ERROR: Sequence Canis_armbrusteri has invalid character 2 at site 5
ERROR: Sequence Canis_dirus has invalid character 2 at site 5
ERROR: Sequence Canis_lupus has invalid character 2 at site 5
ERROR: Sequence Cuon_javanicus has invalid character 2 at site 5
ERROR: Sequence Lycaon_pictus has invalid character 2 at site 5
ERROR: Sequence Cuon_javanicus has invalid character 2 at site 6
ERROR:
```

Strangely enough, no such errors are thrown for `Tedford_2009_MK3.phy`, which is also a short alignment (4 patterns) of 3-state characters.

**Expected behavior**

Correctly detect 3-state characters as such.

**Computer info**

macOS 14.6.1 (Sonoma), IQ-TREE v2.3.5 compiled under Rosetta (i.e., for x86_64).

**Comment by thomaskf** [comment]
Hi @davidcerny
 
I have looked at your partitions.nex file. IQ-TREE detects the partition type based on the specified model, which is working correctly for partitions 1 to 4. However, for partition 5, there is ambiguity because the model `ORDERED` can be interpreted as either binary or morphological data.

To resolve this, you can explicitly specify the data type for partition 5 by updating the partition file with the following line:

```
charset part5 = Tedford_2009_ORDERED3.phy:MORPH,*;
```

After specifying the data type, you also need to indicate the alignment region. The `*` symbol represents the entire alignment in the file.

This should enable the program to run without issues.

Thomas

**Comment by thomaskf** [comment]
Hi David,

Thank you for taking the time to look at the source code.

The function I was referring to is `detectSeqType()` in the file `phylotesting.cpp`. When a model is assigned to a partition, this function is initially called to detect the partition’s data type based on the specified model.

For partition 5, where the model is set to `ORDERED`, this function cannot determine the data type, which is why I suggested explicitly specifying the data type for partition 5 to avoid ambiguity.

When `detectSeqType()` is unable to identify the data type, the program then calls the function `Alignment::detectSequenceType` (the one you mentioned) as a secondary approach to determine the type.

Specifically, if at least 90% of the characters in the alignment (excluding gaps) match a particular data type, the function classifies the partition as that type. This logic applies universally across data types, not just for binary or morphological data. Since over 90% of partition 5 contains 0 or 1, it was categorized as binary. 

I understand your suggestion. However, modifying the logic exclusively for binary data would create inconsistency of the logic across data types.

Thomas

**Comment by davidcerny** [comment]
Thank you for this detailed explanation; it's very helpful! I can see now why `ORDERED` can't be used for data type detection even though morphology is the only data type it works with.

> Specifically, if at least 90% of the characters in the alignment (excluding gaps) match a particular data type, the function classifies the partition as that type. This logic applies universally across data types, not just for binary or morphological data. Since over 90% of partition 5 contains 0 or 1, it was categorized as binary.

I think that logic makes a lot of sense when it comes to distinguishing DNA from protein sequences, where there is an overlap in the symbols used (amino acid letter abbreviations vs. IUPAC nucleotide ambiguity codes). You'd hope that you wouldn't run into a DNA alignment that consists almost entirely of ambiguities, or into a protein alignment that consists almost entirely of alanine (`A`), cysteine (`C`), glycine (`G`), and threonine (`T`). So it makes sense to handle things probabilistically. But with binary data, the only non-ambiguous residues you can observe are `0` and `1` – if you observe some others as well, then, by definition, your data are not really binary.

I would still respectfully suggest a code change.

**Comment by thomaskf** [comment]
Thank you for the suggestion. I appreciate it. After a second thought, I agree that binary data, unlike other data types, contains no ambiguous characters other than gaps. I will discuss this with @bqminh. Thanks!

**Comment by thomaskf** [comment]
Hi David,
Thanks again for looking at the codes and suggesting the changes.
After talking with Minh, he also agrees with your suggestion.
Would you like to create a PR for this?
Thomas

**Comment by davidcerny** [comment]
Hi @thomaskf, that's great – thank you! I just opened a PR for the suggested code change. I'm sorry it took me a while – I found it pretty hard to recompile IQ-TREE on my Macbook. But now I've done it, and can confirm that the code change does fix the issue.
