### ISSUE TITLE
alisim error with input tree

### ISSUE THREAD

**Issue by meganlsmith** [iqtree/iqtree2#63]
Hello,

I am trying to use alisim to simulate data on a user-provided input tree. This generally works well, but occasionally I get the following error: 

ERROR: Redundant double-bracket ‘((…))’ with closing bracket ending at (line 1 column 419)

The tree file in question does not end with a double-bracket, and it can be read by other programs (e.g., ete3, FigTree). I have attached the input tree in question. The command I'm using to run alisim is: 

~/Documents/Programs/iqtree-2.2.0-beta-MacOSX/bin/iqtree2 --alisim test -t ./test3.txt -m JC --length 100
[test3.txt](https://github.com/iqtree/iqtree2/files/8218354/test3.txt)

Thanks for any insight you can provide!

Best,
Megan

**Comment by trongnhanuit** [comment]
Dear Megan,
Your tree should look like this 
<img width="353" alt="image" src="https://user-images.githubusercontent.com/7534124/157561549-616e7072-ab4c-4518-aacf-2209a3d8c166.png">

Although FigTree can read your tree, it ignores the last branch (connecting to root with length 0.025497) without any warning. 
<img width="779" alt="image" src="https://user-images.githubusercontent.com/7534124/157560212-c5f5703f-0681-4734-94d8-5c8e46c79e97.png">
Since ignoring a branch leads to incorrect simulation, we show an error in AliSim. You can resolve that problem by merging the the two branches as follows.
<img width="904" alt="image" src="https://user-images.githubusercontent.com/7534124/157561364-4116dab0-d8ad-41f8-948a-c24ddb6e8d49.png">
This is your tree after merging
[test3_merged.txt](https://github.com/iqtree/iqtree2/files/8219132/test3_merged.txt)

I'll check whether we can automatically detect and merge branches like these cases and make that feature available in the next release of AliSim (if possible). In the mean time, you can convert your trees (if neccessary) manually as follows.
<img width="306" alt="image" src="https://user-images.githubusercontent.com/7534124/157563800-33b3a947-fa65-4410-b623-713319e0c78f.png">

Cheers,
Nhan

**Comment by roblanf** [comment]
@trongnhanuit that's such an amazingly helpful reply! 

I have one suggestion for the next release. Rather than automatically doing this (which I think might lead to more problems than it's worth), I would suggest the following as the default behaviour:

1. Auto-detect this, and if it's detected, print out a warning that explains the issue as you did in your post above (you could even print out little ASCII trees to explain it, since your explanation above is so clear)

2. In the warning message, offer the users a non-default option something like `--merge-root-branches` to do what's in your last example.

3. In the warning message, offer the users another non-default option something like `--trim-root-branch` that would instead of merging the two root branches, just trim off the bottom one (i.e. doing what FigTree does in your example above).

You could illustrate both options 2 and 3 in your warning message using ASCII trees.

**Comment by meganlsmith** [comment]
Thanks for the very quick and helpful reply @trongnhanuit and @roblanf. It makes sense that this was causing an issue. The trees shouldn't have this branch; it was an issue in some other simulation code I was using to generate the trees. I'll just plan on fixing these prior to running alisim. Thanks again!

**Comment by akezhuoli** [comment]
i meant same problem,and my tree file is quite large,manually merge thouse no-branch-inner-node is too hard.so i write a function to help merge no-branch-inner-node
# use biopython
def merge_redundant_nodes(tree):
    no_redundant_nodes = False
    for clade in tree.find_clades():
        if clade.is_terminal():
            continue
        children = list(clade)
        if len(children) == 1:
            child = children[0]
            clade.name = child.name
            clade.branch_length = clade.branch_length + child.branch_length
            clade.clades = child.clades
            no_redundant_nodes = True
    if no_redundant_nodes:
        merge_redundant_nodes(tree)
after merge_redundant_nodes(tree) my tree pass check from https://github.com/corneliusroemer/nwk-formatter .

Finally, my iqtree command runs sunccessful.
constrain tree check of iqtree is serious, redundant innner node in tree lead error.
