### ISSUE TITLE
Less models which have been shown in the log file

### ISSUE THREAD

**Issue by 473021677** [iqtree/iqtree2#64]
Hi,
[Uploading gtdbtk.bac120.user_msa.phy.log…]()

  I am using IQ-TREE 2.1.3 to build the phylogenomic tree. Everything seems OK and the tree file is generated. But when I look up the log file, the number of the protein models which have been shown is 117, and is not 702. I am not sure if there's something wrong with it. I really need your help. If you could help, I really appreciate. I have appended the log file.

Best regards,
YangYuan

**Comment by bqminh** [comment]
I can't see your log file anymore. But this is a normal behaviour: We have introduced a heuristic to "prune" non-promising models, so that not all models have to be tested. There is a more recent discussion #193 that provides more context to that. We will follow it up there, instead of this one. Thus, I will mark this as duplicated.
