### ISSUE TITLE
[Enhacement] Using IQtree log file to create alignment parameters

### ISSUE THREAD

**Issue by noahaus** [iqtree/iqtree2#66]
Thank you for creating a quick and thorough tool for alignment simulation! 

Let's say I have an alignment and ModelFinder through iqtree states that HKY is the best model for my alignment. 
Now I want to take the inferred aspects of my alignment and simulate it using Alisim. Is there a way to take previous iqtree log output and run alisim based on the specifications in the log file?

Would it just be easier to take my current alignment and just let Alisim compute the appropriate models and then do the simulation? Any help on this would be greatly appreciated.

**Comment by trongnhanuit** [comment]
Dear @noahaus,
Thank you for your suggestion. In fact, we have just implemented that feature a few days ago. We're providing two options to simulate new alignments by mimicking an input alignment as follows.

**Option 1: Automatically mimicking the input alignment**
Users only need to supply an input alignment. AliSim natively runs IQ-TREE to infer model parameters and a phylogenetic tree from the input alignment, then simulates new alignments from the inferred tree and model. For more details, please have a look at [http://www.iqtree.org/doc/AliSim#mimicking-a-real-alignment](http://www.iqtree.org/doc/AliSim#mimicking-a-real-alignment) 
-> This feature is already available in [IQ-TREE 2.2.0-beta](https://github.com/iqtree/iqtree2/releases/tag/v2.2-beta).

**Option 2: Semi-automatically mimicking the input alignment**
 Users run IQ-TREE to infer model parameters and a phylogenetic tree. IQ-TREE automatically prints a command to run AliSim in the IQ-TREE log file (*.log), which can be used to simulate new alignments later from the inferred tree and model. Users can modify the command before running AliSim (e.g, if they want to use the inferred model with a different tree). 
Due to the implementation complexity, that feature does not yet work with complex models (e.g., mixture, lie-markov models). 
-> Currently, you can now use that feature by compiling the latest source code of IQ-TREE. We'll officially provide that feature in the next release (in the next few days).

Cheers,
Nhan

**Comment by Chjulian** [comment]
Hey @trongnhanuit, is option 2 already implemented? The `-h` of iqtree2 (compiled for Mac OS X 64-bit, built Apr 21 2022) informs:

`--export-alisim-cmd  Export a command-line from the inferred tree and model params' `

But when I try to use it I get the error: 

`Invalid "--export-alisim-cmd" option.`

I also tried with the last binary for Mac OS X 64-bit built Jun  1 2022. Same result.

Best,
Julián

**Comment by trongnhanuit** [comment]
Hi Julián,
For users' convenience, IQ-Tree automatically exports AliSim's command into (the end of) the output file (*.iqtree). You don't need to use `--export-alisim-cmd` (I'll remove it from the help `-h`). Please feel free to contact me if you have any questions. 
Cheers,
Nhan

**Comment by Chjulian** [comment]
Hi Nhan, I found it! 
Many thanks!
Cheers
Julián
