### ISSUE TITLE
IQtree not writing varsites.phy after using ASC correctly

### ISSUE THREAD

**Issue by mwersebe** [iqtree/iqtree2#74]
Hi I am running IQtree version 2.2.0-beta for Linux installed via bioconda. I am trying to infer a phylogeny using SNP data. After converting my VCF to phylip format and running this command line:

`iqtree -s file.phy -m GTR+ASC -B 1000 -T AUTO`

I get the error that my phylip file has invariant sites and that IQtree has written a new file called prefix.varsites.phy

When I rerun the the command above the with the new varsites.phy file IQtree quits with an error saying:

`ERROR: Sequence SAMPLE1 contains too many characters (890048)`

I checked the varsites.phy file with the following commands:
'head -n1 file.varsites.phy' 

Which returns the correct number of samples and the correct number of sites after removing invariant sites in the header line:

`89 417199`

However the actual alignments do not have the invariant sites removed with many more sites :

`head -n2 file.varsites.phy| tail -n1 |awk -F " " '{print$2}' |wc`

`1       1  890056`

Not sure if this a bug in the conda version. I was not able to recreate the issue with another version:
IQtree version 2.0 installed on another computer. 

Thank you!

**Comment by thomaskf** [comment]
Hi Matt,
Thanks for your question. Can you send us your new varsites.phy file for us to check?
According to the error, it seems that the length of SAMPLE1 is too long.
Thanks,
Thomas

**Comment by mwersebe** [comment]
[PulexGroup_Phylogeny.min4.phy.varsites.phy.log](https://github.com/iqtree/iqtree2/files/8431463/PulexGroup_Phylogeny.min4.phy.varsites.phy.log)
[PulexGroup_Phylogeny.min4.phy.log](https://github.com/iqtree/iqtree2/files/8431464/PulexGroup_Phylogeny.min4.phy.log)
Do you have a preferred email? Git hub won't allow me to upload it here. Thanks!

Matt

**Comment by thomaskf** [comment]
Hi Matt,
Can you send the varsites.phy file to my email address: Thomas.Wong@anu.edu.au ?
Thanks,
Thomas

**Comment by thomaskf** [comment]
Hi Matt,

Thanks for sending me the data.

I have just fixed the issue. Please refer to the updated release v2.2.0.1: https://github.com/iqtree/iqtree2/releases/tag/v2.2.0.1

Please rerun the following command line by using this updated release for your original phylip file:

`
iqtree -s file.phy -m GTR+ASC -B 1000 -T AUTO
`

Same as before, you will then get an error saying that the phylip file has invariant sites and then IQtree will report a new file called prefix.varsites.phy

Previously the varsites.phy file was not correct. This time it should work when you rerun the command above with this new varsites.phy file.

Hope the problem can be fixed. Please confirm.

Thanks again for reporting the issue.

Thomas

**Comment by Yyeserin** [comment]
Hi Thomas,

I have a similar problem. I  work with SNP data. 

When I use the code below, IQtree (iqtree-2.2.0-Windows) creates a new phylipp file:

_iqtree2 -s 92INDS.ORIGINAL.dna.PHY.txt -st DNA -m TEST+ASC -B 1000 -T AUTO_

ERROR: For your convenience alignment with variable sites printed to 92INDS.ORIGINAL.DNA.txt.varsites.phy
ERROR: Invalid use of +ASC because of 1497 invariant sites in the alignment

But when I ran the newly created file, the program complains as below for each sample:

_ERROR: Sequence SPA_Sp6 contains too many characters (9868)_

The newly created files still have the invariant sites. What can be the problem with my data?

Many thanks!
Yeserin.

**Comment by thomaskf** [comment]
Hi Yeserin,
This bug should have been fixed, but not in your current version. Can you please try version 2.2.0.8 https://github.com/iqtree/iqtree2/releases/tag/v2.2.0.8  and see whether the same problem still exists? Please rerun the command for creating the new phylip file.
Best regards,
Thomas

**Comment by KatherinOtalora** [comment]
Hello 

I had the same error about .variants and I solved it by downloading the latest version. When running the following line: 

> /Users/katherin_otalora/Documents/iqtree-2.2.0.8-MacOSX/bin/iqtree2 -s nonrev_allsamples_new_version.varsites.fasta -m 12.12 -m GTR+ASC -B 1000 -T AUTO -st DNA --prefix nonrev_allsamples_new_version_1.

I get the following outputs:

Consensus tree written to nonrev_allsamples_new_version_1.contree.
Reading the input tree file nonrev_allsamples_new_version_1.contree
Log-likelihood of the consensus tree: -5501.780

Analysis results written in: 
  IQ-TREE report: nonrev_allsamples_new_version_1.iqtree
  Maximum likelihood tree: nonrev_allsamples_new_version_1.treefile
  Likelihood distances: nonrev_allsamples_new_version_1.mldist

Results of ultrafast bootstrap approximation written in:
  Split support values: nonrev_allsamples_new_version_1.splits.nex
  Consensus tree: nonrev_allsamples_new_version_1.contree
  Screen log file: nonrev_allsamples_new_version_1.log

But I am looking for the **name.rootstrap.nex**, I see a splits.nex here, is this the same as the .rootstrap in the new version?

Thank you,

**Comment by imaa9** [comment]
Hi Thomas, 

I'm running IQ-TREE multicore version 2.2.2 (COVID-edition for Linux 64-bit built Apr 12 2023) and am having similar issues to what is being described above for the varsites file generation. 

When I run 
> iqtree2 -s mtDNA_MISS75.phy -m MFP+ASC -B 1000 --prefix test_mtdna -nt AUTO --safe

I get the error,
> Alignment was printed to test_mtdna.varsites.phy
> ERROR: For your convenience alignment with variable sites printed to test_mtdna.varsites.phy
> ERROR: Invalid use of +ASC because of 39 invariant sites in the alignment

The header to my original file has 97 4199 for the count of samples and sequence length, respectively. 

When I inspect the new varsites file created, the header displays 97 4160, but when I try to run iq-tree, it fails as follows:
> iqtree2 -s test_mtdna.varsites.phy -m MFP+ASC -B 1000 --prefix test_mtdna -nt AUTO --safe

> Reading alignment file test_mtdna.varsites.phy ... Phylip format detected
> ERROR: Sequence A contains too many characters (4199)
> ERROR: Sequence B contains too many characters (4199)
> ERROR: Sequence C....

It appears that the number at the top has been adjusted in the new varsites file, but this adjustment isn't reflected in the length of the sequences, which are still 4199 as in the original file. 

Happy to hear any guidance you might have on resolving this issue. Thanks very much, Inbar

**Comment by thomaskf** [comment]
Hi,

There have been some bugs fixed after this version. Can you try version v2.2.2.4 (at https://github.com/iqtree/iqtree2/releases/tag/v2.2.2.4) and see whether the problem still exists? If the problem is still there, can you send us the alignment files so we can check on our side?

Thanks,
Thomas

**Comment by juliagrp** [comment]
Hi! Same problem.. Im using the latest version installed with Conda:
 IQ-TREE multicore version 2.2.2.7 COVID-edition for Linux 64-bit built Jun  7 2023
And gives me the same error...
Reading alignment file 171_pruned0.9.min4.phy.varsites.phy ... Phylip format detected
ERROR: Sequence Adriano contains too many characters (504812)
...
Any idea?

**Comment by KatherinOtalora** [comment]
I was able to solve this by running the following line: 

./iqtree2 -s allsamples_consensus_15samples_gt096.fasta -m GTR+ASC -B 1000 -T AUTO -pre allsamples_consensus_15samples_gt096_

**Put -st DNA in case you have very long sequences.**

#Then the same program will give you an output named varsites.phy that removes the invariant sites, you can check it and then use that varsites.phy for your analysis. 

./iqtree2 -s allsamples_consensus_15samples_gt096.varsites.phy --model-joint 12.12 -B 1000 -T AUTO -pre NOrev_invariant_allsamples_B1K

This might work!!!

**Comment by juliagrp** [comment]
Hi KatherinOtalora!

Thanks for your fast response :) 

It works!! just adding the **-st DNA**  param as you suggest!

I run first: 
**iqtree -s 171_pruned0.9.min4.phy -m GTR+ASC -B 1000 -T 8 -st DNA**
It gives me this out:
ERROR: For your convenience alignment with variable sites printed to **171_pruned0.9.min4.phy.varsites.phy**
ERROR: Invalid use of +ASC because of 176022 invariant sites in the alignment

Then I ran:
**iqtree -s 171_pruned0.9.min4.phy.varsites.phy -m GTR+ASC -B 1000 -T 8 -st DNA**
Now its still running for the final output, but the last print was...
--------------------------------------------------------------------
|             INITIALIZING CANDIDATE TREE SET                      |
--------------------------------------------------------------------
Generating 98 parsimony trees... 
 
Lets see how many time takes to finish and I've works well, by the moment it has good appearance.

**Comment by lmarieslava** [comment]
Hi! I'm having this same issue with IQTREE 2.2.2 I tried the -st DNA flag as well but I still get it:

iqtree2 -s vcf_filter3_preHWE_preLD_rmIDS_NEWPHY.phy -st DNA -m GTR+ASC --prefix outgroup -B 1000 -T AUTO -o "14_sorted,33_sorted,9_sorted"
iqtree2 -s vcf_filter3_preHWE_preLD_rmIDS_NEWPHY.phy -st DNA -m GTR+ASC --prefix loci -T AUTO -o "14_sorted,33_sorted,9_sorted"

Then I get the ERROR: Invalid use of +ASC because of X invariant sites in the alignment

And I try to input the .varsites.phy file like so:

iqtree2 -s outgroup.varsites.phy -st DNA -m GTR+ASC --prefix outgroup -B 1000 -T AUTO -o "14_sorted,33_sorted,9_sorted"
iqtree2 -s loci.varsites.phy -st DNA -m GTR+ASC --prefix loci -T AUTO -o "14_sorted,33_sorted,9_sorted"

To which I get ERROR: Sequence 1_sorted contains too many characters (30986)
For all of my individuals senquences. 

Any clues?

**Comment by thomaskf** [comment]
Hi @lmarieslava ,

This issue should have been resolved in the latest version, which can be downloaded at https://github.com/iqtree/iqtree2/releases ? 

Cheers,
Thomas
