### ISSUE TITLE
would the order of the sequences in my alignment change the final tree?

### ISSUE THREAD

**Issue by csanchis** [iqtree/iqtree2#83]
Hello! I have to concatenate some genes already aligned, and in the final alignment probably the order of the sequences in the initial alignment (done with mafft) will be changed. Is it important for making the tree (the sequences won't change)?

**Comment by thomaskf** [comment]
Hello,
Thanks for your quesiton. The order of the genes (or sites) will not affect the result of the tree.

**Comment by csanchis** [comment]
thank you very much for your answer

**Comment by bqminh** [comment]
Sorry, I have to correct @thomaskf 's answer. The question was about the order of sequences, not genes or sites. The answer is: the order of sequences may change the final tree. 
In fact, the order of genes or sites may also change the final tree.

And even for the very same alignment, different runs may produce different trees because IQ-TREE is a stochastic algorithm. In fact in the document:

http://www.iqtree.org/doc/Command-Reference#tree-search-parameters

We suggest users to run 10 times (with/without changing the default parameters) and compare the results. The bottom line is that IQ-TREE implements a heuristic algorithm and there is no guarantee that it finds the global optimum as tree search is an NP-hard problem. This statement also holds for RAxML or any other tree search algorithms.
