### ISSUE TITLE
[recipe wanted] Using Simulated Alignments for Statistical Hypothesis Testing

### ISSUE THREAD

**Issue by noahaus** [iqtree/iqtree2#89]
I have been using Alisim as a way to test for interesting genomic regions amongst bacterial whole genome sequences.

 For instance, let's say we have 100 tuberculosis isolates from a fictitious town and we are interested in finding regions in the mTB genome that experienced higher than average mutation. If we just used the original data, we might resort to just using outliers determined through non-parametric means (i.e. boxplot). 
 
 However, Alisim can simulate random sequences that follow the same evolutionary history as the phylogeny! Not only that, the simulated alignment can be built using the extensive substitution models provided by IQTree. This leads to an interesting use of Alisim: we can create statistical null distributions of sequence data that match closely with the evolutionary history of original data. Statistical Hypothesis testing can then be used to detect regions with significantly high differences compared to the simulated alignment. 

I was wondering if this would be a cool recipe to add, because if this was made accessible, we could interrogate genomic data in a more intimate way.  

Best,

**Comment by roblanf** [comment]
Hi @noahaus, I like this idea, but I’d need more information to really put something together here.

What I need to know is what your test statistic is. I.e. in a parametric bootstrap we typically take some observed value from the data that we’re interested in, and then we simulate datasets under a null model derived from the data to ask how surprised we should be about our observed value.

In your case, it sounds to me like the observed value you’re interested in might be derived from some kind of sliding window analysis on the alignment. E.g. something like: given a sliding window of length N, what’s the expected divergence of the branch lengths (or site rates?) in that sliding window compared to the ML branch lengths (or mean site rates) from the whole alignment. 

In your case, where there is a region of the genome that is evolving a lot faster than the rest, it sounds like you might see one region where the site rates are all elevated. Since this is not part of a standard model of sequence evolution (because we assume sites are IID) that should show up in a sliding window analysis.

I think this is perfectly possible, but I’m not sure it’s really an IQ-TREE recipe - more of an analysis in R perhaps? 

But maybe I’m missing something? Or maybe we should extend recipes to do things in R as well. 

Either way, let me know what you think. And the more details I can figure out about what it is you’re trying to do, the more I can hopefully help.

On a more general note, I think a recipe or two for doing parametric bootstraps in IQ-TREE is a really good idea, then they can be adapted pretty easily to other situations.

**Comment by noahaus** [comment]
@roblanf I understand the dilemma here. I think more generally working on a vignette on how to do parametric bootstrap of data with Alisim would be a better approach here. 

If you are thinking of working on something like this - please reach out. I can send you a confidential draft of my manuscript where I use this method and maybe we can discuss a simple example how to generate a bootstrap value (I've never made a vignette before so I'd be open to help out). I also have some command line + python scripts that would be potentially helpful for demonstration!

I'll close the comment but please reach out again if you have any questions

**Comment by roblanf** [comment]
Excellent. I'll try to make the smallest possible example of a parametric bootstrap that I can. Then that can be adapted to pretty much any situation.

**Comment by noahaus** [comment]
Hello! 

I wanted to update you that I have my paper published that used the exact approach we described here a few months ago - check this out:
https://www.frontiersin.org/articles/10.3389/fmicb.2022.787856/full

Materials and Methods  - Simulated Mycobacterium bovis alignment

If you have any questions please reach out!

**Comment by roblanf** [comment]
@noahaus - cool! I'll take a look when I get a chance. Ping me here again soon if I forget.
