### ISSUE TITLE
ERROR: alignment.cpp:81: std::__cxx11::string& Alignment::getSeqName(int): Assertion `i >= 0 && i < seq_names.size()' failed.

### ISSUE THREAD

**Issue by bladrome** [iqtree/iqtree2#97]
tail in logs

```
ERROR: 59   PhyloTree::assignLeafNames(Node*, Node*)
ERROR: 60   PhyloTree::assignLeafNames(Node*, Node*)
ERROR: 61   PhyloTree::assignLeafNames(Node*, Node*)
ERROR: 62   PhyloTree::assignLeafNames(Node*, Node*)
ERROR: 63   PhyloTree::assignLeafNames(Node*, Node*)
ERROR:
ERROR: *** IQ-TREE CRASHES WITH SIGNAL ABORTED
ERROR: *** For bug report please send to developers:
ERROR: ***    Log file: all_noval_bin.log
ERROR: ***    Alignment files (if possible)
```

As mentioned in [issue 38](https://github.com/iqtree/iqtree2/issues/38), it is unfinished, but i did NOT change the -s option

print i and the seq_names.size()
```
in getSeqName, i = 6367 seqname.size:1719
```

**Comment by thomaskf** [comment]
Hi ,
Please use the latest version 2.2.0.5 (https://github.com/iqtree/iqtree2/releases).
The issue #38 happened because the varsites file was not created correctly. The bug should have been fixed in the latest version. Please use the latest version to create the varsites file again.
If the problem still exists, it will be helpful for us to identify the problem if you can also send us the alignment file.
Best regards,
Thomas
