### ISSUE TITLE
NO BP values in trees

### ISSUE THREAD

**Issue by Mirror1211** [iqtree/iqtree2#98]
Hi,
I used iqtree to construct phylogentic trees, but there was no BS values in these trees in two nodes. 
Commandline: iqtree -s zj_0.9.fasta -nt 6 -m JTT+F+R5 -bb 10000 -safe -bnni
![image](https://user-images.githubusercontent.com/39644316/180588571-7c0ee8c4-59f8-4091-9d10-a1582fd62423.png)
Then, I defined the outgroup to redo these analyses, but the issue still occurred.
Commandline: iqtree -s zj_0.9.fasta -nt 6 -m JTT+F+R5 -bb 10000 -safe -o out1 -bnni
![image](https://user-images.githubusercontent.com/39644316/180589555-ece5f14b-0ff7-4e29-bbe1-dc1c3e64fc39.png)
How should I deal with this issue ???? Thanks.

**Comment by heikotree** [comment]
Dear ‘what-ever-your-name-is’,

> On 23.07.2022, at 05:17, Mirror1211 ***@***.***> wrote:
> 
> 
> Hi,
> I used iqtree to construct phylogentic trees, but there was no BS values in these trees in two nodes.
> Commandline: iqtree -s zj_0.9.fasta -nt 6 -m JTT+F+R5 -bb 10000 -safe -bnni
> 
> Then, I defined the outgroup to redo these analyses, but the issue still occurred.
> Commandline: iqtree -s zj_0.9.fasta -nt 6 -m JTT+F+R5 -bb 10000 -safe -o out1 -bnni
> How should I deal with this issue ???? Thanks.

The output is correct, because you have an UFboot support value for each internal branch.

I think there is a misunderstanding, how the support values are computed… I will try to explain this in the following.

The support values are associated to branches, not nodes.
Technically the support values are written after the bracket of an inner node, but they relate to the branch in the direction of the (virtual) root (i.e. the outer-most bracket in the Newick string). The is the same branch the branch length relates to that is following the support value after the colon.

Why are support values only computed for inner branches, that means branches which have at least two leafs/taxa on either side?

What is typically done is that from a set of many tree it is computed how often (in what percentage of the trees) does a branch occur.
That means more precisely - each branch imposes a split into two sets of leafs/taxa.

For instance, a tree like “((A,B),C,(D,E));” has two internal branches, associate with the splits AB|CDB (A and B on one side while C,D,E are on the other) and ABC|DE (A,B,C on one side, D and E on the other). 
Another tree could be “((A,B),(C,D),E));” where the existing splits are AB|CDE (as in the tree before) and ABE|CD.

Those would be counted for instance from your 10000 UFboot trees that you made IQ-Tree compute by setting “-bb 10000”.

Those splits that have only one leaf/taxon on one side, are so called trivial splits, because these always have to be in all trees. Otherwise some leafs/taxa would not be linked to the tree.

In the two small 5-taxon trees above these trivial splits are A|BCDE, ACDE|B, ABDE|C, ABCE|D and ABCD|E. Since these always occur they would always have a support value of 100%, hence they are called ’trivial’ and are typically not reported in a tree.


Let’s look at your tree - If I understand you question correctly you wonder why there is not support value on the branch that has the work ‘bootstrap’ above it and the one that leads to the bulk of the tree - correct?

The reason is the following. During the reconstruction, no branch to the root exists. By setting the unlabeled top taxon (out1?) to be the outgroup, that only causes IQ-Tree to output the trees by placing the root into the branch to out1. However, this is your prior knowledge and enforced to the out of IQ-Tree, but cannot be questioned by the program.

Hence, there is no actual root sequence, that would enable IQ-Tree to check the placement of that user-imposed root.
That means in reality the branch from the bulk of the tree to out1 is just a single external branch. That also means it cannot give you a reasonable support value for the placement of the root, because that value will be 100% by definition.

The pink circle that is closest to the root, tells you what is the support that out1 and the second lowest leaf in your tree cluster together. And this is the only information any phylogenetic software can provide from such an analysis.

If you want question the placement of the root, you might be able to do this, if you provide another outgroup sequence related to out1, and maybe another one closely related to the 2nd-deepest leaf sequence in you tree.


However, please keep in mind that the choice of outgroup sequence is far from trivial.
If they are too distant to you ingroup they might well cluster together, but they might connect to the ingroup sequences at a non-reliable position. As an extreme example, think of trying to root the tree of human, chimp, Orangutan with two proteo-bacteria.
On the other hand, if the outgroup is too close to the ingroup it might not provide the information to separate from the ingroup.

Checkout for example the following paper about problems with rooting trees:

Sanderson and Shaffer (2002)
   Troubleshooting Molecular Phylogenetic Analyses.
   Annu. Rev. Ecol. Syst. 33, 49-72
   http://dx.doi.org/10.1146/annurev.ecolsys.33.010802.150509


I hope I could help.

Best wishes,
Heiko 


-----------------------------------------------------------------------------
Heiko Schmidt
Vienna, Austria
-----------------------------------------------------------------------------

**Comment by zzbbf123** [comment]
Thanks for your detailed answer, it resolved a long-standing confusion of mine. I want to reopen this issue to ask, since node A|BCDE is referred to as a "trivial"  and always has a 100% support value, can i manually assign a 100% support value to this node?
